#ifndef SDCONFIG_H
#define SDCONFIG_H

#define CONFIG_BT_ENABLED 1
#define CONFIG_BT_NIMBLE_ENABLED 1
//#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL 1
#define CONFIG_BT_NIMBLE_HID_DEVICE 1

#endif /* SDCONFIG_H */
